# Generated by Django 4.0 on 2021-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAdset',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_id', models.CharField(max_length=255)),
                ('lifetime_budget', models.DecimalField(decimal_places=2, max_digits=5)),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('targeting', models.JSONField()),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=255)),
                ('optimization_goal', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyCampaign',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('objective', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
