# Generated by Django 4.0 on 2021-12-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_myadcreative_object_story_spec'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAdImage',
            fields=[
                ('hash', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
