# Generated by Django 3.2.1 on 2021-12-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_myadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myadset',
            name='bid_amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myadset',
            name='daily_budget',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myadset',
            name='lifetime_budget',
            field=models.CharField(max_length=255),
        ),
    ]
